project_id = "hfojxbfcjozguobwtcgt"

[db]
major_version = 15

[functions.c2b-webhook]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.mpesa-b2c-callback]
verify_jwt = false

[functions.send-case-reminders]
verify_jwt = false

[functions.api-sms-templates]
verify_jwt = false

[functions.api-notifications-mark-read]
verify_jwt = false

[functions.api-notifications-list]
verify_jwt = false

[functions.api-settings]
verify_jwt = false

[functions.api-sms-summary]
verify_jwt = false

[functions.api-members-list]
verify_jwt = false

[functions.mpesa-reversal]
verify_jwt = false

[functions.mpesa-reversal-callback]
verify_jwt = false
