import { useEffect, useState } from 'react';
import DashboardLayout from '@/layouts/DashboardLayout';
import { invokeWithAppToken } from '@/lib/appAuth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { toast } from '@/components/ui/use-toast';

type Application = { id: string; application_reference: string; full_name: string; national_id_number: string; date_of_birth: string; phone_number: string; residence_status: string; village?: string; current_location?: string; status: string; application_date: string; payment_reference?: string; review_reason?: string };

export default function Applications() {
  const [applications, setApplications] = useState<Application[]>([]); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const result = await invokeWithAppToken<{ applications: Application[] }>('api-membership-applications', { action: 'list' }); setApplications(result.applications || []); } catch (error) { toast({ variant: 'destructive', title: 'Failed to load applications', description: error instanceof Error ? error.message : 'Please try again.' }); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const review = async (application: Application, decision: 'approve' | 'reject') => { const reason = decision === 'reject' ? window.prompt('Reason for rejection (optional):') || '' : ''; try { await invokeWithAppToken('api-membership-applications', { action: 'review', application_id: application.id, decision, reason }); toast({ title: decision === 'approve' ? 'Application approved' : 'Application rejected' }); void load(); } catch (error) { toast({ variant: 'destructive', title: 'Review failed', description: error instanceof Error ? error.message : 'Please try again.' }); } };
  const confirmPayment = async (application: Application) => { if (!window.confirm('Confirm that the registration fee has been received and activate this member?')) return; try { const result = await invokeWithAppToken<{ member_number: string; probation_end_date: string }>('api-membership-applications', { action: 'confirm_payment', application_id: application.id }); toast({ title: 'Membership activated', description: `${result.member_number}; probation ends ${result.probation_end_date}` }); void load(); } catch (error) { toast({ variant: 'destructive', title: 'Activation failed', description: error instanceof Error ? error.message : 'Please try again.' }); } };
  return <DashboardLayout><div className="space-y-6"><div><h1 className="text-3xl font-bold">Membership Applications</h1><p className="text-muted-foreground">Review online self-registration submissions and request registration-fee payment.</p></div><Card><CardHeader><CardTitle>{loading ? 'Loading…' : `${applications.length} applications`}</CardTitle></CardHeader><CardContent className="space-y-3">{applications.map((application) => <div className="rounded-lg border p-4" key={application.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{application.full_name}</p><p className="text-sm text-muted-foreground">{application.application_reference} · ID {application.national_id_number} · {application.phone_number}</p><p className="text-sm">{application.residence_status === 'resident' ? application.village : application.current_location}</p></div><Badge variant={application.status === 'rejected' ? 'destructive' : 'secondary'}>{application.status.replaceAll('_', ' ')}</Badge></div>{application.status === 'pending_review' && <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => void review(application, 'approve')}>Approve and request payment</Button><Button size="sm" variant="outline" onClick={() => void review(application, 'reject')}>Reject</Button></div>}{application.payment_reference && <p className="mt-3 text-sm font-medium">Payment reference: {application.payment_reference}</p>}{application.status === 'payment_pending' && <div className="mt-3"><Button size="sm" onClick={() => void confirmPayment(application)}>Confirm payment and activate</Button></div>}</div>)}{!loading && applications.length === 0 && <p className="text-sm text-muted-foreground">No applications received.</p>}</CardContent></Card></div></DashboardLayout>;
}
